# API
services:
  postgrex:
    container_name: postgrex-mono
    build:
      context: apps/api/tools/docker/db
      dockerfile: Dockerfile
      args:
        - CRON_DATABASE_NAME=${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
    networks:
      - dev

  mapapi:
    container_name: mapapi-mono
    build:
      context: apps/api
      dockerfile: tools/docker/Dockerfile
    command: npm run start:dev
    ports:
      - 3001:3001
    volumes:
      - ./apps/api/src:/app/src
    networks:
      - dev
    depends_on:
      - postgrex

  app:
    container_name: website-mono
    build:
      context: apps/website
      target: build
    ports:
      - "3000:3000"
    volumes:
      - ./apps/website:/app
      - /app/node_modules
      - ./apps/website/.nuxt:/app/.nuxt
    command: npm run dev
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development

networks:
  dev:
    driver: bridge

volumes:
  pgdata:

