# Dockerfile.dev
FROM node:22-slim

WORKDIR /app

ENV NODE_ENV=development
ENV HOST=0.0.0.0
ENV PORT=3000

# Install dependencies
COPY package.json package-lock.json .npmrc ./

RUN npm install



# Copy source code
COPY . .

# Expose your dev port (change if needed)
EXPOSE 3000

# Default command: run dev server with hot reload
CMD [ "npm", "run", "dev" ]
